language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "harisson-freitas"
    token:
      secure: "$SONAR_TOKEN" # encrypted value of your token

script:
  - ./gradlew sonarqube
